name:               "Mat Munn"
description:        "A web developer based in Melbourne, Australia"

url:                "https://matmunn.me"
author:             "Mat Munn"
email:              "mat@matmunn.me"
gravatar_hash:      "38f71ad48c5e9eedcafcab49744328a6"
twitter:            "matmunn"
github:             "matmunn"
linkedin:           "matmunn"

paginate:           8
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Contact"
    href:           "/contact"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
